FROM amazonlinux:2

# Install required packages

RUN amazon-linux-extras install -y epel && yum update -y && yum install -y nginx

# Expose ports

EXPOSE 80

EXPOSE 443


# Start Nginx

CMD ["nginx", "-g", "daemon off;"]
